-- ============================================
-- Insertion complète du menu dans la base de données
-- Tous les plats depuis menuData.js
-- ============================================

-- Récupérer les IDs des catégories
SET @cat_pizzas = (SELECT id FROM cat WHERE nom = 'Pizzas');
SET @cat_pates = (SELECT id FROM cat WHERE nom = 'Pâtes');
SET @cat_enfants = (SELECT id FROM cat WHERE nom = 'Enfants');
SET @cat_salade = (SELECT id FROM cat WHERE nom = 'Salade');
SET @cat_dessert = (SELECT id FROM cat WHERE nom = 'Dessert');
SET @cat_boisson = (SELECT id FROM cat WHERE nom = 'Boisson');
SET @cat_options = (SELECT id FROM cat WHERE nom = 'Options');

-- ============================================
-- PIZZAS
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_pizzas, '4 Fromages classic', 'tomate, fromage, gorgonzola, bel paese, taleggio', 14.00, 1, 1),
(@cat_pizzas, '4 saisons classic', 'tomate, fromage, champignons, jambon, olives, artichauts', 14.00, 1, 2),
(@cat_pizzas, 'Al Capone classic', 'tomate, fromage, chorizo, oignons, capres', 13.50, 1, 3),
(@cat_pizzas, 'Al Pacino classic', 'tomate, fromage, jambon, poivrons, anchois, oeuf, pili-pili', 14.00, 1, 4),
(@cat_pizzas, 'Alba', 'tomate, fromage, chips de parme, roquette, parmesan, tomates cerises, burrata, creme de pistache, pistache', 21.00, 1, 5),
(@cat_pizzas, 'Ali Baba', 'tomate, fromage, salami turc, poivrons, olives', 14.00, 1, 6),
(@cat_pizzas, 'Antartique', 'tomate, fromage, scampis, saumon, oignons, citron, ail', 20.00, 1, 7),
(@cat_pizzas, 'Ardenaise classic', 'lardons, oignons, oeuf frais', 13.00, 1, 8),
(@cat_pizzas, 'Arlequin', 'Spécialité maison', 16.50, 1, 9),
(@cat_pizzas, 'Barbecue classic', 'tomate, fromage, saucisses, lardons, merguez, oignons, poivrons', 14.00, 1, 10),
(@cat_pizzas, 'Bolo', 'Sauce bolognaise', 12.00, 1, 11),
(@cat_pizzas, 'Braisée', 'lardons, pommes de terre, oignons, oeufs frais, mozzarella, crème', 14.00, 1, 12),
(@cat_pizzas, 'Brocoli', 'fromage, brocoli,oignons, poulet, ail, crème', 14.00, 1, 13),
(@cat_pizzas, 'Bufala', 'creme, fromage, chorizo, roquette, bufala, pistache', 16.50, 1, 14),
(@cat_pizzas, 'Calzone classic', 'tomate, fromage, jambon, champignons, oeuf dur, ail (pizza fermée)', 12.50, 1, 15),
(@cat_pizzas, 'Campagnarde classic', 'tomate, fromage, thon, fromage de chèvre, oignons', 13.50, 1, 16),
(@cat_pizzas, 'Cannibale', 'tomate fromage saucisse merguez poulet lardon hache de boeuf 2 oeufs frais', 18.00, 1, 17),
(@cat_pizzas, 'Capris classic', 'tomate, fromage, champignons, jambon, oeuf dur', 13.50, 1, 18),
(@cat_pizzas, 'Caramel classic', 'tomate, fromage, chèvre, oignons, miel', 13.00, 1, 19),
(@cat_pizzas, 'Casablanca', 'tomate, sucuk, fromage, oignons, poivrons', 14.00, 1, 20),
(@cat_pizzas, 'Castellane', 'tomate,fromage, tomate fraiche, mozzarella fraiche, pesto', 13.50, 1, 21),
(@cat_pizzas, 'Catane', 'Crème, oignions, courgette, scampis, pesto', 15.50, 1, 22),
(@cat_pizzas, 'Chicken barbecue', 'tomate, formage, poulet, poivrons, oignons, sc bbq', 14.00, 1, 23),
(@cat_pizzas, 'Chorizo classic', 'tomate, fromage, chorizo', 11.50, 1, 24),
(@cat_pizzas, 'Cow Boy', 'sce BBQ, fromage, poulet, haché de boeuf, cheddar, concombre', 15.50, 1, 25),
(@cat_pizzas, 'Deniro classic', 'tomate, fromage, salami, champignons, olives', 13.00, 1, 26),
(@cat_pizzas, 'Diabolique classic', 'tomate, fromage, chorizo, poivrons, champignons, pili-pili', 13.00, 1, 27),
(@cat_pizzas, 'Duchesse', 'mozzarella, saucisses, pommes de terre, crème, oignons, lardons', 14.00, 1, 28),
(@cat_pizzas, 'Dürüm', 'crème,fromage, kebab, concombre, tomates fraîches, aîoli', 15.50, 1, 29),
(@cat_pizzas, 'El Greco', 'tomate,fromage,poulet,poivrons,feta,olives', 15.00, 1, 30),
(@cat_pizzas, 'El Toro classic', 'tomate, fromage, boulettes de boeuf, poivrons, olives', 13.50, 1, 31),
(@cat_pizzas, 'Emmenthal classic', 'Tomate, fromage, jambon, gruyère, oeufs frais', 13.50, 1, 32),
(@cat_pizzas, 'Epervier', 'formage, Chorizo, pdt, merguez, haché de boeuf, tomate fr', 17.50, 1, 33),
(@cat_pizzas, 'Exotic classic', 'tomate, fromage, thon, ananas', 13.00, 1, 34),
(@cat_pizzas, 'Fermière', 'crème, fromage, jambon, tomates caramélisées, courgette, oeuf frais', 15.50, 1, 35),
(@cat_pizzas, 'Feta classic', 'tomate, fromage, feta, olive, tomates fraiches', 13.50, 1, 36),
(@cat_pizzas, 'Forestière', 'Tomate, Fromage, Oignons, Champignons, Lardons, Origan', 12.50, 1, 37),
(@cat_pizzas, 'Fruit de mer', 'Sauce tomate, fromage, fruits de mer', 14.50, 1, 38),
(@cat_pizzas, 'Full Option', 'tomate, fromage, salami, jambon, champignons, anchois, capres, olives, oeuf frais', 16.00, 1, 39),
(@cat_pizzas, 'Funghi', 'Tomate, fromage, champignions', 11.50, 1, 40),
(@cat_pizzas, 'Grill', 'tomate, fromage, saucisses, lardons, merguez, oignons, tomates fraiches', 14.50, 1, 41),
(@cat_pizzas, 'Grimbergen', 'fromage,jambon,oignons,fromage de grimbergen', 14.50, 1, 42),
(@cat_pizzas, 'Hamburger', 'tomate, fromage, sce barbecue, oignons, champignons, hamburger', 14.50, 1, 43),
(@cat_pizzas, 'Hawaï classic', 'tomate, fromage, jambon, ananas', 12.50, 1, 44),
(@cat_pizzas, 'Istanbul classic', 'tomate, fromage, saucisse turque, olives, pili-pili', 13.50, 1, 45),
(@cat_pizzas, 'Kebab', 'Tomate, fromage, oignons, Feta, Viandes Kebab, Olives', 15.50, 1, 46),
(@cat_pizzas, 'Mafiosi classic', 'tomate, fromage, salami, jambon, oignons, capres', 13.00, 1, 47),
(@cat_pizzas, 'Maison classic', 'tomate, fromage, hachée de boeuf, champignons, oignons, crème', 13.50, 1, 48),
(@cat_pizzas, 'Maitre corbeau', 'creme vacherin fribourgeois gruyere bresie roquette (hiver)', 15.50, 1, 49),
(@cat_pizzas, 'Manon', 'crème, fromage, oignons, talegio, jambon, roquette, balsamique', 15.50, 1, 50),
(@cat_pizzas, 'Maredsous classic', 'tomate, fromage, fromage de maredsous', 12.50, 1, 51),
(@cat_pizzas, 'Margharitta classic', 'tomate, double fromage', 10.50, 1, 52),
(@cat_pizzas, 'Marrakech classic', 'tomate, fromage, saucisse turque, gorgonzola', 13.50, 1, 53),
(@cat_pizzas, 'Marseillaise classi', 'tomate, fromage, poulet, tomates, courgettes', 13.50, 1, 54),
(@cat_pizzas, 'Maxim', 'Tomate, fromage, blanc de poulet, Mozzarella fraiche, courgette, oeufs durs, ail', 15.50, 1, 55),
(@cat_pizzas, 'Méditerrannée class', 'tomate, fromage, scampis, poivrons, oignons, ail', 14.50, 1, 56),
(@cat_pizzas, 'Merguez classic', 'tomate, fromage, merguez, oignons, tomates fraiches', 13.50, 1, 57),
(@cat_pizzas, 'Mexicaine', 'tomate, haché de boeuf, poivron, maïs, oignon,jambon, cheddar, piment', 17.50, 1, 58),
(@cat_pizzas, 'Miami', 'tomate, fromage, tomates caramélisées, haché de boeuf, cheddar', 15.50, 1, 59),
(@cat_pizzas, 'Milanaise classic', 'tomate, fromage, fromages,thon, capres, oeuf dur', 13.00, 1, 60),
(@cat_pizzas, 'Mont Blanc', 'Crème, 4 fromages', 14.00, 1, 61),
(@cat_pizzas, 'Montana classic', 'tomate, fromage, chèvre, lardons, oignons', 13.50, 1, 62),
(@cat_pizzas, 'Namuroise classic', 'tomate, fromage, saucisses, tomates fraiches, oignons', 13.50, 1, 63),
(@cat_pizzas, 'Napolitaine classic', 'tomate, fromage, anchois, capres, ail', 12.50, 1, 64),
(@cat_pizzas, 'New Yorkaise', 'sce pepper, jambon, tomates fraîches, roquette, cheddar', 16.00, 1, 65),
(@cat_pizzas, 'Ortolona', 'Tomate, fromage, aubergine, poivrons, parmesan', 13.50, 1, 66),
(@cat_pizzas, 'Paradis classic', 'tomate, fromage, salami, chorizo, jambon, ail, pili', 13.00, 1, 67),
(@cat_pizzas, 'Parme', 'Tomate, fromage, jambon de parme', 13.50, 1, 68),
(@cat_pizzas, 'Parmiggiana', 'tomate, fromage, aubergine, jambon, copeaux de parmesan', 16.50, 1, 69),
(@cat_pizzas, 'Paysanne classic', 'tomate, fromage, chorizo, artichauts, champignons, olives', 14.00, 1, 70),
(@cat_pizzas, 'Pekin', 'tomate, fromage, poulet, champignons, oignons, aigre-doux', 14.50, 1, 71),
(@cat_pizzas, 'Pepper', 'Sauce poivre, fromage, oignons, tomate fraîche, blanc de poulet, haché de boeuf', 15.00, 1, 72),
(@cat_pizzas, 'Pesto', 'Tomate, fromage, oignions, chèvre, pesto', 14.00, 1, 73),
(@cat_pizzas, 'Pompéi', 'tomate, fromage, tomates caramélisées, roquette, copeaux de parmesan', 14.50, 1, 74),
(@cat_pizzas, 'Printanière classic', 'tomate, fromage, poulet, champignons, artichauts, olives', 14.00, 1, 75),
(@cat_pizzas, 'Proscuitto classic', 'tomate, fromage, jambon', 11.50, 1, 76),
(@cat_pizzas, 'Raclette', 'tomate, fromage, fromage à Raclette, jambon', 14.50, 1, 77),
(@cat_pizzas, 'Regina classic', 'tomate, fromage, champignons, jambon, olives', 12.50, 1, 78),
(@cat_pizzas, 'Romaine classic', 'tomate, fromage, jambon,courgettes,tomate,huile d olive', 13.50, 1, 79),
(@cat_pizzas, 'Roquette', 'Tomate fromage jambon roquette', 14.50, 1, 80),
(@cat_pizzas, 'Ruccola', 'tomate, fromage, jambon, roquette, tomate-cerise, parmesan', 15.50, 1, 81),
(@cat_pizzas, 'Saisonnière', 'tomate, fromage, jambon, artichauts, poivrons, anchois, olives, oeuf', 15.50, 1, 82),
(@cat_pizzas, 'Salami classic', 'tomate, double fromage, salami', 11.50, 1, 83),
(@cat_pizzas, 'Saumon classic', 'tomate, fromage, saumon fumé, oignons, citron', 15.50, 1, 84),
(@cat_pizzas, 'Scampis', 'Tomate, fromage, scampis, tomate fraiche, ail', 14.50, 1, 85),
(@cat_pizzas, 'Siciliène classic', 'tomate, fromage, anchois, olives, ail', 12.50, 1, 86),
(@cat_pizzas, 'Spécial Brocoli', 'fromage, brocoli,oignons, poulet, lardons, ail, crème', 15.50, 1, 87),
(@cat_pizzas, 'Special Gourmande', 'tomate,fromage,tomate fr,mozza fr,oignons,lardons,basilique,olives', 15.50, 1, 88),
(@cat_pizzas, 'special parme', 'tomate,from, jambon, gorgo,roquette', 14.50, 1, 89),
(@cat_pizzas, 'Spéciale Caramel', 'tomate, fromage, chèvre, oignons, miel, lardons', 14.00, 1, 90),
(@cat_pizzas, 'Spéciale Grill', 'tomate, fromage, saucisses, lardons, merguez, oignons, tomates fraiches, haché', 16.50, 1, 91),
(@cat_pizzas, 'Spéciale Maredsous', 'tomate, fromage, fromage de mardesous, lardons', 13.50, 1, 92),
(@cat_pizzas, 'tacos el chapo', 'mozzarella haché de boeuf blanc de poulet piment frais pdt oignon poivron cheddar', 14.00, 1, 93),
(@cat_pizzas, 'tacos escobar', 'mozzarella poulet jambon haché de boeuf pdt oignon cheddar', 13.00, 1, 94),
(@cat_pizzas, 'tacos la Quica', 'mozzarella saucisse merguez poulet pdt cheddar', 14.00, 1, 95),
(@cat_pizzas, 'tacos ochoa', 'mozzarella hache de boeuf chorizo salami pdt cheddar', 14.00, 1, 96),
(@cat_pizzas, 'Tahiti', 'Tomate, fromage, blanc de poulet, ananas', 12.50, 1, 97),
(@cat_pizzas, 'Tartiflette', 'pommes de terre, lardons, oignons, roblochon, crème', 14.50, 1, 98),
(@cat_pizzas, 'Tartufo', 'cr de truffe noire,mozza,roqu,tom-cerises,parmesan,vinaigre balsm', 17.00, 1, 99),
(@cat_pizzas, 'Thaïlandaise', 'tomate, fromage, poulet, poivrons, oeuf dur, pili-pili', 13.50, 1, 100),
(@cat_pizzas, 'Toupie', 'crème, fromage, oignions , chèvre , poulet, pesto', 15.50, 1, 101),
(@cat_pizzas, 'Trim', 'creme de pistache, mozzarella, jambon, bufala, pistache, roquette', 18.50, 1, 102),
(@cat_pizzas, 'Végétarienne', 'tomate, fromage, courgettes, tomates, artichauts, poivrons, olives', 14.50, 1, 103);

-- ============================================
-- PÂTES
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_pates, 'Lasagne', 'tomates, crème', 11.50, 1, 1),
(@cat_pates, 'Penne Arrabiata', 'tomate, oignons, pili-pili', 11.50, 1, 2),
(@cat_pates, 'Penne Bolo crème', 'Bolognaise à la crème', 11.50, 1, 3),
(@cat_pates, 'Penne Bolognaise', 'Traditionnelle', 11.50, 1, 4),
(@cat_pates, 'Penne Bouba', 'Lardons, champignons, jambon, oignons, ail, crème, tomate', 13.50, 1, 5),
(@cat_pates, 'Penne Carbonara', 'Crème, lardons, oeuf', 12.50, 1, 6),
(@cat_pates, 'Penne Démoniak', '6 Scampi, sce Tomate, crème, pili', 14.50, 1, 7),
(@cat_pates, 'Penne du Chef', 'tomates, jambon, champignons, ail, crème', 13.00, 1, 8),
(@cat_pates, 'Penne Forestière', 'Crème, Oignons, Lardons, Champignons', 13.00, 1, 9),
(@cat_pates, 'Penne Saumon Fumé', 'Crème, Saumon, Echalotte, Sce Tomate, Ail', 15.00, 1, 10),
(@cat_pates, 'Spgt Carbonara', 'Traditionnelle à l\'italienne', 12.50, 1, 11),
(@cat_pates, 'Tagl Saumon Fumé', 'Saumon, crème et fines herbes', 15.50, 1, 12),
(@cat_pates, 'Tagl toscane', 'Tomate fraiches, crème, 6 scampis, ail, basilic', 15.50, 1, 13);

-- ============================================
-- ENFANTS
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_enfants, 'Enfant Babybel', 'Tomate, fromage, babybel', 7.50, 1, 1),
(@cat_enfants, 'Enfant Bolo', 'Sauce bolognaise', 7.50, 1, 2),
(@cat_enfants, 'Enfant Chorizo', 'Tomate, fromage, chorizo', 7.50, 1, 3),
(@cat_enfants, 'Enfant Hawaï', 'Tomate, fromage, jambon, ananas', 7.50, 1, 4),
(@cat_enfants, 'Enfant Margharitta', 'Tomate, fromage', 7.50, 1, 5),
(@cat_enfants, 'Enfant Proscuitto', 'Tomate, fromage, jambon', 7.50, 1, 6),
(@cat_enfants, 'Enfant Salami', 'Tomate, fromage, salami', 7.50, 1, 7);

-- ============================================
-- SALADE
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_salade, 'X2 Pain à l\'ail', '2 pièces', 3.50, 1, 1),
(@cat_salade, 'X2 Pain à l\'ail + lardon', '', 4.50, 1, 2),
(@cat_salade, 'Assiette italienne', '', 13.50, 1, 3),
(@cat_salade, 'Burrata bomb', 'pâte à pizza farcie, burrata, pesto vert et éclats de pistache', 12.00, 1, 4);

-- ============================================
-- DESSERT
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_dessert, 'Bavarois au Speculoos', 'glace speculoos, biscuit, gateau', 6.50, 1, 1),
(@cat_dessert, 'Bavarois framboise', 'mousse framboise, gateau, biscuit', 6.50, 1, 2),
(@cat_dessert, 'Pizza Nutella', '', 7.50, 1, 3);

-- ============================================
-- BOISSON
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_boisson, 'Coca Cola 1.5L', '', 5.50, 1, 1),
(@cat_boisson, 'Coca Cola 33cl', '', 2.50, 1, 2),
(@cat_boisson, 'Coca Zéro', '', 2.50, 1, 3),
(@cat_boisson, 'Coca zero 1.5l', '', 5.50, 1, 4),
(@cat_boisson, 'Eau Pétillante 33 Cl', '', 2.00, 1, 5),
(@cat_boisson, 'Eau Plate 33 Cl', '', 2.00, 1, 6),
(@cat_boisson, 'Fanta 1.5L', '', 5.50, 1, 7),
(@cat_boisson, 'Fanta 33 cl', '', 2.50, 1, 8),
(@cat_boisson, 'Ice Tea 33 cl', '', 2.50, 1, 9),
(@cat_boisson, 'Ice Tea Pèche 33 Cl', '', 2.50, 1, 10),
(@cat_boisson, 'Schweppes Agrum 33 Cl', '', 2.50, 1, 11),
(@cat_boisson, 'Sprite 1,5L', '', 5.50, 1, 12),
(@cat_boisson, 'Sprite 33 Cl', '', 2.50, 1, 13),
(@cat_boisson, 'Tropico', '', 2.50, 1, 14);

-- ============================================
-- OPTIONS
-- ============================================
INSERT INTO `carte` (`cat_id`, `nom`, `description`, `prix`, `actif`, `ordre`) VALUES
(@cat_options, 'pili appart', '', 0.50, 1, 1),
(@cat_options, 'Pizza 40cm', '', 10.50, 1, 2),
(@cat_options, 'sans aigres-doux', '', 0.00, 1, 3),
(@cat_options, 'sans ail', '', 0.00, 1, 4),
(@cat_options, 'sans ail et pili', '', 0.00, 1, 5),
(@cat_options, 'sans aioli', '', 0.00, 1, 6),
(@cat_options, 'sans ananas', '', 0.00, 1, 7),
(@cat_options, 'sans anchoix', '', 0.00, 1, 8),
(@cat_options, 'sans artichaut', '', 0.00, 1, 9),
(@cat_options, 'Sans aubergine', '', 0.00, 1, 10),
(@cat_options, 'sans blanc de poulet', '', 0.00, 1, 11),
(@cat_options, 'sans bolo', '', 0.00, 1, 12),
(@cat_options, 'sans brocoli', '', 0.00, 1, 13),
(@cat_options, 'sans câpres', '', 0.00, 1, 14),
(@cat_options, 'sans champignons', '', 0.00, 1, 15),
(@cat_options, 'sans chedar', '', 0.00, 1, 16),
(@cat_options, 'sans chèvres', '', 0.00, 1, 17),
(@cat_options, 'sans chorizo', '', 0.00, 1, 18),
(@cat_options, 'sans citron', '', 0.00, 1, 19),
(@cat_options, 'sans concombre', '', 0.00, 1, 20),
(@cat_options, 'sans cornichons', '', 0.00, 1, 21),
(@cat_options, 'sans coulis de tomate', '', 0.00, 1, 22),
(@cat_options, 'sans courgettes', '', 0.00, 1, 23),
(@cat_options, 'sans crème', '', 0.00, 1, 24),
(@cat_options, 'sans feta', '', 0.00, 1, 25),
(@cat_options, 'sans fromage', '', 0.00, 1, 26),
(@cat_options, 'sans gorgonzola', '', 0.00, 1, 27),
(@cat_options, 'sans Grmbergen', '', 0.00, 1, 28),
(@cat_options, 'sans haché', '', 0.00, 1, 29),
(@cat_options, 'sans huile d\'olive', '', 0.00, 1, 30),
(@cat_options, 'sans jambon', '', 0.00, 1, 31),
(@cat_options, 'sans jambon de parme', '', 0.00, 1, 32),
(@cat_options, 'sans lardons', '', 0.00, 1, 33),
(@cat_options, 'sans mais', '', 0.00, 1, 34),
(@cat_options, 'sans merguez', '', 0.00, 1, 35),
(@cat_options, 'sans miel', '', 0.00, 1, 36),
(@cat_options, 'sans mozzarella', '', 0.00, 1, 37),
(@cat_options, 'sans oeufs durs', '', 0.00, 1, 38),
(@cat_options, 'sans oeufs frais', '', 0.00, 1, 39),
(@cat_options, 'sans oignons', '', 0.00, 1, 40),
(@cat_options, 'sans olive', '', 0.00, 1, 41),
(@cat_options, 'sans origan', '', 0.00, 1, 42),
(@cat_options, 'sans parmesan', '', 0.00, 1, 43),
(@cat_options, 'sans pesto', '', 0.00, 1, 44),
(@cat_options, 'sans pili', '', 0.00, 1, 45),
(@cat_options, 'sans piment', '', 0.00, 1, 46),
(@cat_options, 'sans poivrons', '', 0.00, 1, 47),
(@cat_options, 'sans pommes de terre', '', 0.00, 1, 48),
(@cat_options, 'sans reblochon', '', 0.00, 1, 49),
(@cat_options, 'sans roquette', '', 0.00, 1, 50),
(@cat_options, 'sans salami', '', 0.00, 1, 51),
(@cat_options, 'sans sauce balsamique', '', 0.00, 1, 52),
(@cat_options, 'sans sauce barbecue', '', 0.00, 1, 53),
(@cat_options, 'sans sauce poivre', '', 0.00, 1, 54),
(@cat_options, 'sans saucisse', '', 0.00, 1, 55),
(@cat_options, 'sans scampis', '', 0.00, 1, 56),
(@cat_options, 'sans sucuk', '', 0.00, 1, 57),
(@cat_options, 'sans thon', '', 0.00, 1, 58),
(@cat_options, 'sans tomate fraiche', '', 0.00, 1, 59),
(@cat_options, 'sans tomates caramelisees', '', 0.00, 1, 60),
(@cat_options, 'sans tomates cerises', '', 0.00, 1, 61),
(@cat_options, 'sans viande de dinde', '', 0.00, 1, 62),
(@cat_options, 'sans viande Kebap', '', 0.00, 1, 63),
(@cat_options, 'sans vinaigre balsamique', '', 0.00, 1, 64),
(@cat_options, 'supp piments frais', '', 2.00, 1, 65),
(@cat_options, 'supp. 4 fromages', '', 3.00, 1, 66),
(@cat_options, 'supp. aigre-doux', '', 2.00, 1, 67),
(@cat_options, 'supp. ail', '', 0.00, 1, 68),
(@cat_options, 'supp. ail et pili', '', 0.00, 1, 69),
(@cat_options, 'supp. aioli', '', 1.50, 1, 70),
(@cat_options, 'supp. ananas', '', 1.50, 1, 71),
(@cat_options, 'supp. anchoix', '', 1.50, 1, 72),
(@cat_options, 'supp. artichaut', '', 1.50, 1, 73),
(@cat_options, 'supp. aubergines', '', 2.00, 1, 74),
(@cat_options, 'supp. Blanc de Poulet', '', 2.00, 1, 75),
(@cat_options, 'supp. capres', '', 1.50, 1, 76),
(@cat_options, 'supp. champignons', '', 1.50, 1, 77),
(@cat_options, 'supp. chedar', '', 2.00, 1, 78),
(@cat_options, 'supp. Chèvre', '', 2.00, 1, 79),
(@cat_options, 'supp. Chorizo', '', 2.00, 1, 80),
(@cat_options, 'supp. concombre', '', 1.50, 1, 81),
(@cat_options, 'supp. coulis de tomate', '', 1.50, 1, 82),
(@cat_options, 'supp. courgettes', '', 1.50, 1, 83),
(@cat_options, 'supp. crème', '', 0.50, 1, 84),
(@cat_options, 'supp. crème pâtes', '', 1.50, 1, 85),
(@cat_options, 'supp. feta', '', 3.00, 1, 86),
(@cat_options, 'supp. fromage Grimbergen', '', 3.00, 1, 87),
(@cat_options, 'supp. fromage maredsous', '', 3.00, 1, 88),
(@cat_options, 'supp. fromage raclette', '', 3.00, 1, 89),
(@cat_options, 'supp. Gorgonzola', '', 2.00, 1, 90),
(@cat_options, 'supp. gruyère', '', 1.50, 1, 91),
(@cat_options, 'supp. Haché de Boeuf', '', 2.00, 1, 92),
(@cat_options, 'supp. huile d\'olive', '', 0.50, 1, 93),
(@cat_options, 'supp. jambon', '', 1.50, 1, 94),
(@cat_options, 'supp. lardons', '', 1.50, 1, 95),
(@cat_options, 'supp. mais', '', 1.50, 1, 96),
(@cat_options, 'supp. melon', '', 2.00, 1, 97),
(@cat_options, 'supp. merguez', '', 2.00, 1, 98),
(@cat_options, 'supp. miel', '', 1.50, 1, 99),
(@cat_options, 'supp. mozza fraiche', '', 2.00, 1, 100),
(@cat_options, 'supp. mozzarella', '', 2.00, 1, 101),
(@cat_options, 'supp. oeuf frais', '', 1.50, 1, 102),
(@cat_options, 'supp. oeufs dur', '', 1.50, 1, 103),
(@cat_options, 'supp. oignons', '', 1.50, 1, 104),
(@cat_options, 'supp. olives', '', 1.50, 1, 105),
(@cat_options, 'supp. origan', '', 0.00, 1, 106),
(@cat_options, 'supp. pain', '', 2.50, 1, 107),
(@cat_options, 'supp. parmesan', '', 2.00, 1, 108),
(@cat_options, 'supp. pesto', '', 1.50, 1, 109),
(@cat_options, 'supp. pili', '', 0.00, 1, 110),
(@cat_options, 'supp. piment frais tres piquant', '', 1.00, 1, 111),
(@cat_options, 'supp. poivrons', '', 1.50, 1, 112),
(@cat_options, 'supp. Pommes de Terre', '', 2.00, 1, 113),
(@cat_options, 'supp. reblochon', '', 2.00, 1, 114),
(@cat_options, 'supp. roquette', '', 1.00, 1, 115),
(@cat_options, 'supp. salami', '', 1.50, 1, 116),
(@cat_options, 'supp. sauce aioli tacos', '', 0.00, 1, 117),
(@cat_options, 'supp. sauce algérienne ta', '', 0.00, 1, 118),
(@cat_options, 'supp. sauce andalouse tac', '', 0.00, 1, 119),
(@cat_options, 'supp. sauce barbecue', '', 2.00, 1, 120),
(@cat_options, 'supp. sauce ketchup tacos', '', 0.00, 1, 121),
(@cat_options, 'supp. sauce mayonnaise ta', '', 0.00, 1, 122),
(@cat_options, 'supp. Saucisse', '', 2.00, 1, 123),
(@cat_options, 'supp. Saumon Fumé', '', 3.00, 1, 124),
(@cat_options, 'supp. Scampis', '', 3.00, 1, 125),
(@cat_options, 'supp. Sce poivre', '', 2.50, 1, 126),
(@cat_options, 'supp. Sucuk', '', 2.00, 1, 127),
(@cat_options, 'supp. tallegio', '', 1.50, 1, 128),
(@cat_options, 'supp. thon', '', 1.50, 1, 129),
(@cat_options, 'supp. tomate fraiche', '', 1.50, 1, 130),
(@cat_options, 'supp. tomates caramalisee', '', 1.50, 1, 131),
(@cat_options, 'supp. Tomates Cerises', '', 1.50, 1, 132),
(@cat_options, 'supp. vinaigre balsamique', '', 1.00, 1, 133),
(@cat_options, 'supp. vinaigrette', '', 0.50, 1, 134),
(@cat_options, 'supp.sauce poivre tacos', '', 0.00, 1, 135),
(@cat_options, 'suppl. viande Kebap', '', 3.00, 1, 136);
